name: Deploy Projects

on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Initialize Repository if Missing
        run: ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
            if [ ! -d .git ]; then 
            git init && 
            git remote add origin https://github.com/adseun/github-actions-demo-project/;
          fi"

      - name: Pull Repository
        run: ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
          cd /home/demo &&
          git fetch origin &&
          git checkout ${{ secrets.MAIN_BRANCH }} &&
          git pull origin ${{ secrets.MAIN_BRANCH }}"
